CREATE TABLE Users (
	ID_USER SERIAL PRIMARY KEY,
	NAME_USER VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	PASSOWORD_HASH VARCHAR(255) NOT NULL,
	CREATE_AT TIMESTAMP NOT NULL,
	UPDATED_T TIMESTAMP NOT NULL
);

CREATE TABLE Applications (
    ID_APP SERIAL PRIMARY KEY,
    ID_USER_FK INT NOT NULL REFERENCES Users(ID_USER),
    COMPANY VARCHAR(150) NOT NULL,
    SECTOR VARCHAR(150),
    COMPANY_LINKEDIN VARCHAR(500),
    CITY VARCHAR(100),
    PLATFORM VARCHAR(100),
    JOB_TITLE VARCHAR(150) NOT NULL,

    LEVEL VARCHAR(50) CHECK (
        LEVEL IN ('INTERN', 'JUNIOR', 'MID', 'SENIOR')
    ),

    WORK_MODEL VARCHAR(30) CHECK (
        WORK_MODEL IN ('REMOTE', 'HYBRID', 'ONSITE')
    ),

    APPLICATION_DATE DATE NOT NULL,

    STATUS VARCHAR(50) NOT NULL CHECK (
        STATUS IN (
            'SAVED',
            'APPLIED',
            'INTERVIEW',
            'TECHNICAL_TEST',
            'APPROVED',
            'REJECTED'
        )
    ),

    RECRUITER VARCHAR(150),
    CONTACT VARCHAR(255),
    SALARY DECIMAL(10,2),
    JOB_URL VARCHAR(500),
    NOTES TEXT,

    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
